export default [
  {
    id: "0ca88a56-a19a-11eb-bcbc-0242ac130002",
    content: {
      blocks: [
        {
          key: "9tik9",
          text: "Noteworthy 📝",
          type: "header-one",
          depth: 0,
          inlineStyleRanges: [
            {
              offset: 0,
              length: 12,
              style: "UNDERLINE",
            },
          ],
          entityRanges: [],
          data: {},
        },
        {
          key: "99hbq",
          text: "An editor worthy of your notes.",
          type: "header-two",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "9vkn4",
          text: "Some of the things Noteworthy is capable of:",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [
            {
              offset: 0,
              length: 44,
              style: "ITALIC",
            },
            {
              offset: 19,
              length: 10,
              style: "BOLD",
            },
          ],
          entityRanges: [],
          data: {},
        },
        {
          key: "ev32c",
          text: "Different headings (Title, Heading, Body).",
          type: "unordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "6nun7",
          text: "Inline styles such as bold, italic, underline, highlight, strikethrough and code.",
          type: "unordered-list-item",
          depth: 0,
          inlineStyleRanges: [
            {
              offset: 22,
              length: 4,
              style: "BOLD",
            },
            {
              offset: 28,
              length: 6,
              style: "ITALIC",
            },
            {
              offset: 36,
              length: 9,
              style: "UNDERLINE",
            },
            {
              offset: 47,
              length: 9,
              style: "HIGHLIGHT",
            },
            {
              offset: 58,
              length: 13,
              style: "STRIKETHROUGH",
            },
            {
              offset: 76,
              length: 4,
              style: "CODE",
            },
          ],
          entityRanges: [],
          data: {},
        },
        {
          key: "31dou",
          text: "Lists, including unordered & ordered lists.",
          type: "unordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "5b657",
          text: "Quotes and codeblocks.",
          type: "unordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "enrri",
          text: "Blockquotes 📢",
          type: "header-two",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "6plpk",
          text: '"Writing, more than any other art, is indexed to the worthiness of the self because it is identified in people\'s minds with emotion." -rachel cusk',
          type: "blockquote",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "c2dbd",
          text: "Codeblocks 🖥",
          type: "header-two",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "3st99",
          text: "toggleBlockType(blockType) {\n  this.onChange(\n    RichUtils.toggleBlockType(\n      this.state.editorState, blockType\n    )\n  );\n}",
          type: "code-block",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "clgmo",
          text: "Ordered List 🔢",
          type: "header-two",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "585a2",
          text: "make a rich text editor",
          type: "ordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {
            checked: true,
          },
        },
        {
          key: "6deno",
          text: "develope a file system",
          type: "ordered-list-item",
          depth: 0,
          inlineStyleRanges: [
            {
              offset: 0,
              length: 22,
              style: "STRIKETHROUGH",
            },
          ],
          entityRanges: [],
          data: {
            checked: false,
          },
        },
        {
          key: "addu1",
          text: "learn back-end development ",
          type: "ordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {
            checked: false,
          },
        },
        {
          key: "5n6n5",
          text: "persist notes to the cloud",
          type: "ordered-list-item",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "c7lff",
          text: "Example Paragraph 🎨",
          type: "header-two",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "5eb16",
          text: "Writing notes should be a minimal, yet powerful experience. Writing notes with Noteworthy is a very clean experience, which leads to a distraction free environment. Together with a large catalog of themes, Noteworthy lets you personalize your experience with zero clutter involved. ",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [
            {
              offset: 0,
              length: 59,
              style: "HIGHLIGHT",
            },
            {
              offset: 100,
              length: 6,
              style: "BOLD",
            },
            {
              offset: 254,
              length: 26,
              style: "BOLD",
            },
            {
              offset: 135,
              length: 16,
              style: "UNDERLINE",
            },
            {
              offset: 254,
              length: 26,
              style: "UNDERLINE",
            },
            {
              offset: 198,
              length: 6,
              style: "ITALIC",
            },
          ],
          entityRanges: [],
          data: {},
        },
        {
          key: "atj88",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "8djjp",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "2gmtp",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "fhg86",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "1bgk3",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "39qol",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
        {
          key: "djld",
          text: "",
          type: "unstyled",
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
      ],
      entityMap: {},
    },
  },
];
